version: '3.1'
services:
  diffusion_api:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "priyanshu"
      POSTGRES_PASSWORD: "anshU11528997!"
      POSTGRES_DB: "diffusion_api"
    ports:
      - "5432:5432"

  redis_test:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"