# Generated by Django 4.2.1 on 2023-05-15 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.TextField(choices=[('LEONARDO_AI', 'LEONARDO_AI')], default='LEONARDO_AI')),
                ('path', models.TextField()),
                ('meta', models.JSONField(default=dict)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'da_images',
                'indexes': [models.Index(fields=['path'], name='da_images_path_5bb468_idx')],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='DLModels',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('hosted', models.TextField(choices=[('HUGGING_FACE', 'HUGGING_FACE')], default='HUGGING_FACE')),
                ('meta', models.JSONField(default=dict)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'da_dl_models',
                'indexes': [models.Index(fields=['name'], name='da_dl_model_name_569890_idx')],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
