# Generated by Django 4.2.1 on 2023-05-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_model_domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dlmodels',
            new_name='da_dlmodels_name_59f037_idx',
            old_name='da_dl_model_name_569890_idx',
        ),
        migrations.AlterModelTable(
            name='dlmodels',
            table='da_dlmodels',
        ),
    ]
