version: '3.1'
services:
  bifrost_test_db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bifrost_test"
    networks:
      - bifrost_test

  bifrost_redis_test:
    image: redis:5.0-alpine
    networks:
      - bifrost_test

  bifrost_rabbitmq_test:
    image: rabbitmq:3.8-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "pwd"
    networks:
      - bifrost_test

  db_migrations:
    build:
      context: ./bifrost
      dockerfile: Dockerfile
    command: python manage.py migrate
    depends_on:
      - bifrost_test_db
      - bifrost_redis_test
      - bifrost_rabbitmq_test
    networks:
      - bifrost_test

  bifrost_tests:
    build: ./bifrost
    command: bash -c "pytest --cov ./ --cov-report xml:test_reports/coverage.xml --junitxml=test_reports/test_report.xml --cov-report html:test_reports/index.html tests/"
    volumes:
      - ./test_reports:/app/test_reports/
    depends_on:
      - bifrost_test_db
      - bifrost_redis_test
      - bifrost_rabbitmq_test
      - db_migrations
    networks:
      - bifrost_test

  bifrost_app:
    build: ./bifrost
    depends_on:
      - bifrost_test_db
      - bifrost_redis_test
      - bifrost_rabbitmq_test
      - db_migrations
    networks:
      - bifrost_test

networks:
    bifrost_test:
